In [ ]:
# https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2023/01-intro/homework.md

In [1]:
import pandas as pd
pd.__version__

'1.4.3'

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
!pip install wget

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9680 sha256=190e55099d1f97a811738dec4f2f448d1da6450ce01ac3c900516ec75ca7a195
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\8b\f1\7f\5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built wget



[notice] A new release of pip available: 22.2.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
!pip install --upgrade pip

  Using cached pip-23.2.1-py3-none-any.whl (2.1 MB)


ERROR: To modify pip, please run the following command:
C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

[notice] A new release of pip available: 22.2.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/AB_NYC_2019.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [10]:
!python -m wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv


Saved under housing.csv


In [2]:
import pandas as pd
df_house=pd.read_csv('housing.csv')

In [3]:
df_house.shape

(20640, 10)

In [4]:
#  select columns with missing data:
missing_values=df_house.isnull()
missing_values.sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [5]:
df_house['ocean_proximity'].nunique()

5

In [6]:
df_house['total_bedrooms'].sum()/df_house['total_bedrooms'].count()

537.8705525375618

In [7]:
df_house['total_bedrooms']=df_house['total_bedrooms'].fillna(537)

In [8]:
#  select columns with missing data:
missing_values=df_house.isnull()


In [9]:
missing_values.sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [10]:
df_house['total_bedrooms'].sum()/df_house['total_bedrooms'].count()

537.8618217054263

In [11]:
#options located on Island
df_house['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [12]:
df_houseIsland=df_house[df_house['ocean_proximity']=='ISLAND']

In [13]:
df_houseIsland.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [14]:

df_houseIsland=df_houseIsland[['housing_median_age','total_rooms','total_bedrooms']]



In [15]:
import numpy as np
X=np.array(df_houseIsland)

In [16]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [17]:
TX=X.T

In [18]:
TX

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [38]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX:
XTXmulmax=np.matmul(TX,X)

In [34]:
XTX=np.dot(X.T,X)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [36]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [39]:
XTXmulmax

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [28]:
# Compute the inverse of XTX.
XTX_inv=np.linalg.inv(XTX)

In [29]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w:
w=np.matmul(np.matmul(XTX_inv,TX),y)

In [42]:
np.dot(np.dot(XTX_inv,TX),y)

array([23.12330961, -1.48124183,  5.69922946])

In [30]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [19]:
import numpy as np
XTX=np.dot(X,TX)

In [20]:
# Calculating the inverse of the matrix
XTXinverse=np.linalg.inv(XTX)
XTXinverse.shape

(5, 5)

In [25]:
y=[950, 1300, 800, 1000, 1300]

In [24]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
inversemul=np.dot(XTXinverse,X)
np.dot(inversemul,Y)

ValueError: shapes (5,3) and (5,) not aligned: 3 (dim 1) != 5 (dim 0)

In [96]:
inverse=np.dot(XTXinverse,X)

In [98]:
np.multiply(inverse,Y)

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [24]:
#  average
df_houseNearbay['median_house_value'].sum()/df_houseNearbay['median_house_value'].count()

259212.31179039303

In [26]:
df_houseNearbay['median_house_value'].sum()


593596194.0

In [27]:
df_houseNearbay['median_house_value'].count()

2290

In [29]:
missing_values=df_houseNearbay['median_house_value'].isnull()
missing_values.sum()

0