In [ ]:
# https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2023/01-intro/homework.md

Question 1<br>
What's the version of Pandas that you installed?

In [1]:
import pandas as pd
pd.__version__

'2.0.3'

Getting the data

In [10]:
!python -m wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv


Saved under housing.csv


In [2]:
import pandas as pd
df_house=pd.read_csv('housing.csv')

Question 2<br>
How many columns are in the dataset?<br>
<br>
- 10
- 6560
- 10989
- 20640

In [3]:
df_house.shape
#  ansewer 10

(20640, 10)

Question 3 <br>
Which columns in the dataset have missing values?<br>
<br>
- total_rooms
- total_bedrooms
- both of the above
- no empty columns in the dataset

In [4]:
#  select columns with missing data:
missing_values=df_house.isnull()
missing_values.sum()
# total_bedrooms

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Question 4<br>
How many unique values does the ocean_proximity column have?
<br>
- 3
- 5
- 7
- 9

In [9]:
df_house['ocean_proximity'].nunique()
# 5

5

What's the average value of the median_house_value for the houses located near the bay?<br>
<br>
- 49433
- 124805
- 259212
- 380440

In [13]:
# df_house['ocean_proximity']=='NEAR BAY'
df_house.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [17]:
# df_house[df_house['ocean_proximity']=='NEAR BAY']['median_house_value'].sum()/len(df_house[df_house['ocean_proximity']=='NEAR BAY'])
df_house[df_house['ocean_proximity']=='NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [10]:
df_house['total_bedrooms'].sum()/df_house['total_bedrooms'].count()

537.8618217054263

In [11]:
#options located on Island
df_house['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [12]:
df_houseIsland=df_house[df_house['ocean_proximity']=='ISLAND']

In [13]:
df_houseIsland.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [14]:

df_houseIsland=df_houseIsland[['housing_median_age','total_rooms','total_bedrooms']]



In [15]:
import numpy as np
X=np.array(df_houseIsland)

In [16]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [17]:
TX=X.T

In [18]:
TX

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [38]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX:
XTXmulmax=np.matmul(TX,X)

In [34]:
XTX=np.dot(X.T,X)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [36]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [39]:
XTXmulmax

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [28]:
# Compute the inverse of XTX.
XTX_inv=np.linalg.inv(XTX)

In [29]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w:
w=np.matmul(np.matmul(XTX_inv,TX),y)

In [42]:
np.dot(np.dot(XTX_inv,TX),y)

array([23.12330961, -1.48124183,  5.69922946])

In [30]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [19]:
import numpy as np
XTX=np.dot(X,TX)

In [20]:
# Calculating the inverse of the matrix
XTXinverse=np.linalg.inv(XTX)
XTXinverse.shape

(5, 5)

In [25]:
y=[950, 1300, 800, 1000, 1300]

In [24]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
inversemul=np.dot(XTXinverse,X)
np.dot(inversemul,Y)

ValueError: shapes (5,3) and (5,) not aligned: 3 (dim 1) != 5 (dim 0)

In [96]:
inverse=np.dot(XTXinverse,X)

In [98]:
np.multiply(inverse,Y)

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [24]:
#  average
df_houseNearbay['median_house_value'].sum()/df_houseNearbay['median_house_value'].count()

259212.31179039303

In [26]:
df_houseNearbay['median_house_value'].sum()


593596194.0

In [27]:
df_houseNearbay['median_house_value'].count()

2290

In [29]:
missing_values=df_houseNearbay['median_house_value'].isnull()
missing_values.sum()

0