In [1]:
#  get the installed pandas version
import pandas as pd
pd.__version__

'2.0.3'

In [3]:
!pip install wget

  Using cached wget-3.2.zip (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py install for wget: started
  Running setup.py install for wget: finished with status 'done'


  DEPRECATION: wget is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
!python -m wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv


Saved under data.csv


In [70]:
#  records in data set
import pandas as pd
df_houseData=pd.read_csv('housedata.csv')
df_houseData.shape[0]

11914

In [71]:
df_houseData.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [72]:
df_houseData['Make'].value_counts().index[:3]



Index(['Chevrolet', 'Ford', 'Volkswagen'], dtype='object', name='Make')

In [73]:
#Show the df_houseData with records where the Make is Audi:
df_houseData[df_houseData['Make']=='Audi']['Model'].nunique()
#  df_houseData[df_houseData['Make']=='Audi']==True

34

In [74]:
df_houseData.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

Question 6
Find the median value of "Engine Cylinders" column in the dataset.
Next, calculate the most frequent value of the same "Engine Cylinders".
Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
Now, calculate the median value of "Engine Cylinders" once again.

In [75]:
med_value=df_houseData['Engine Cylinders'].median()
# 
df_houseData['Engine Cylinders']=df_houseData['Engine Cylinders'].fillna(med_value)

In [76]:
df_houseData.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [77]:
df_houseData['Engine Cylinders'].median()

6.0

Select all the "Lotus" cars from the dataset.
Select only columns "Engine HP", "Engine Cylinders".
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Compute the inverse of XTX.
Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the first element of w?

In [78]:
df_houseDataLotus=df_houseData[df_houseData['Make']=='Lotus']
df_houseDataLotus=df_houseDataLotus[['Engine HP','Engine Cylinders']]

In [82]:
df_houseDataLotus=df_houseDataLotus.drop_duplicates()
df_houseDataLotus.shape

(9, 2)

In [93]:
import numpy as np
X=df_houseDataLotus.to_numpy()

In [84]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [94]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [91]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [87]:
XTX=X@X.T

In [95]:
XTX_2=X.T@X

In [96]:
XTX_2

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [97]:
XTinv=np.linalg.inv(XTX_2)

In [98]:
XTinv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [102]:
y=[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [103]:
w= (XTinv@X.T)@y

In [104]:
w

array([  4.59494481, -63.56432501])

In [105]:
w[0]

4.594944810094551